### ISSUE TITLE
Slug is not defined 

### ISSUE THREAD

**Issue by R0N1n-dev** [JulienVanelian/nuxtjs-graphcms-sakura-starter#2]
Using your example and template but keep getting
"slug is not defined by type postwhereuniqueinput" on slug page. 
What am I doing wrong

**Comment by JulienVanelian** [comment]
Hey!
Do you have a slug field in your GraphCMS schema?

![image](https://user-images.githubusercontent.com/8573006/168791546-a589220e-621e-41c6-8e51-8ab900403cd0.png)

I reproduced your issue by changing my slug field name and id, so I guess this must be the issue here. Either it's a typo, or it's missing.

**Comment by R0N1n-dev** [comment]
Apparently , localization was my issue. Got in touch with GraphCMS staff and got clarification. Slug field was localized. Solved
